# OCTA500 3M 데이터셋 - BerDiff (Bernoulli Diffusion) 학습 설정
model:
  arch_name: berdiff
  image_size: 224
  dim: 64
  timesteps: 100
  learning_rate: 0.0002
  weight_decay: 0.00001
  num_classes: 2
  use_ema: true
  ema_decay: 0.9999
  num_ensemble: 1
  soft_label_type: none
  soft_label_cache: true
  soft_label_fg_max: 11
  soft_label_thickness_max: 13
  soft_label_kernel_ratio: 0.1
  log_image_enabled: true
  log_image_names:
    - '10451.bmp'
    - '10455.bmp'
    - '10460.bmp'

data:
  name: octa500_3m
  train_dir: data/OCTA500_3M/train
  val_dir: data/OCTA500_3M/val
  test_dir: data/OCTA500_3M/test
  crop_size: 224
  train_bs: 8
  num_workers: 8

trainer:
  max_epochs: 500
  accelerator: gpu
  devices: 1
  precision: 32-true  # Binomial distribution은 FP32 필요
  log_every_n_steps: 50
  check_val_every_n_epoch: 10
  accumulate_grad_batches: 2
  gradient_clip_val: 1.0
