# OCTA500 3M 데이터셋 - DSCNet 학습 설정
model:
  arch_name: dscnet
  in_channels: 1
  num_classes: 2
  image_size: 224
  learning_rate: 0.001
  weight_decay: 0.00001
  log_image_enabled: true
  log_image_names:
    - '10451.bmp'
    - '10455.bmp'
    - '10460.bmp'

data:
  name: octa500_3m
  train_dir: data/OCTA500_3M/train
  val_dir: data/OCTA500_3M/val
  test_dir: data/OCTA500_3M/test
  crop_size: 224
  train_bs: 32
  num_workers: 8

trainer:
  max_epochs: 300
  accelerator: gpu
  devices: 1
  precision: 16-mixed
  log_every_n_steps: 50
  check_val_every_n_epoch: 5
