# CSNet - OCTA500 3M Supervised Model Configuration
model:
  arch_name: csnet
  in_channels: 1
  num_classes: 2
  image_size: 224
  learning_rate: 0.001
  weight_decay: 0.00001
  # Image logging to TensorBoard
  log_image_enabled: true

data:
  name: octa500_6m
  train_dir: data/OCTA500_6M/train
  val_dir: data/OCTA500_6M/val
  test_dir: data/OCTA500_6M/test
  crop_size: 224
  train_bs: 32
  num_workers: 8

trainer:
  max_epochs: 300
  accelerator: gpu
  devices: 1
  precision: 32-true
  log_every_n_steps: 50
  check_val_every_n_epoch: 5
  accumulate_grad_batches: 1
  gradient_clip_val: null
  callbacks:
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        monitor: val/dice
        save_last: true
        mode: max
        verbose: true
    - class_path: lightning.pytorch.callbacks.StochasticWeightAveraging
      init_args:
        swa_lrs: 0.0001

  logger:
    class_path: lightning.pytorch.loggers.TensorBoardLogger
    init_args:
      save_dir: lightning_logs
      name: octa500_6m
      version: csnet
