# ROSSA 데이터셋 - nnUNet 스타일 UNet 학습 설정
model:
  arch_name: nnunet
  in_channels: 1
  learning_rate: 0.0002
  weight_decay: 0.00001
  num_classes: 2
  log_image_enabled: false
  log_image_names:
    - '201.png'
    - '205.png'
    - '210.png'

data:
  name: rossa
  train_manual_dir: data/ROSSA/train_manual
  train_sam_dir: data/ROSSA/train_sam
  val_dir: data/ROSSA/val
  test_dir: data/ROSSA/test
  crop_size: 224
  train_bs: 8
  use_sam: false  # true: SAM-annotated 데이터 포함 (618 images)

trainer:
  max_epochs: 300
  accelerator: gpu
  devices: 1
  precision: 32-true
  log_every_n_steps: 10
  check_val_every_n_epoch: 25
  enable_progress_bar: true
  gradient_clip_val: 1.0
  accumulate_grad_batches: 8
